name: voila-gallery-mne
channels:
- conda-forge
dependencies:
- python
- numpy
- scipy
- matplotlib
- ipywidgets
- voila
- ipympl
- pip
- pip:
  - https://github.com/larsoner/mne-python/archive/fwd-dip.zip
