name: voila-gallery-mne
channels:
- conda-forge
dependencies:
- python
- numpy
- scipy
- matplotlib-base
- ipywidgets
- voila
- ipympl
- psutil
- nilearn
- pip
- pip:
  - https://github.com/mne-tools/mne-python/archive/maint/0.20.zip
