name: dipole-demo
channels:
- conda-forge
dependencies:
- python
- numpy
- scipy
- nilearn
- matplotlib-base
- ipywidgets
- voila
- ipympl
- requests
- pip
- pip:
  - https://github.com/mne-tools/mne-python/archive/maint/0.20.zip
